# Generated by Django 4.2.16 on 2024-11-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_card', models.FileField(upload_to='documents/adhar_card/')),
                ('land_documents', models.FileField(upload_to='documents/land_documents/')),
                ('soil_type', models.CharField(max_length=255)),
                ('water_availability', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
