# Generated by Django 4.2.16 on 2024-11-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_documentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
